### ISSUE TITLE
12306 bot查询放票时间报错

### ISSUE THREAD

**Issue by M1saka10010** [touero/carp#47]
[ With version ]
-- python:3.11
-- selenium:4.2.0 4.17.0 4.10.0
-- webdriver:

[ Detailed description ]
-- It is best to provide some screenshot methods to allow reproduction.
2024-01-23 15:12:45,149 - Carp - INFO ==> 'WebElement' object has no attribute 'find_element_by_xpath'
2024-01-23 15:12:45,151 - Carp - INFO ==> Traceback (most recent call last):
  File "D:\Code\carp\src\robot_master.py", line 55, in start_task
    self.robot.run_task()
  File "D:\Code\carp\robots\railway_robot.py", line 16, in run_task
    self.check_time()
  File "D:\Code\carp\robots\railway_robot.py", line 61, in check_time
    station = row.find_element_by_xpath('.//div[@class="sale-station-name"]').text
              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebElement' object has no attribute 'find_element_by_xpath'
我看4.3之后selenium砍掉了这个函数，但是_re已经改好了，不知道还有哪里有问题

**Comment by touero** [comment]
re当中覆盖的是driver对象的，而`find_element_by_xpath`原本是之前selenium版本中的WebElement对象的，所以出现了错误，而在新版这个WebElement对象的`find_element_by_xpath`变为了`find_element`的形式，同时貌似必须指定By的方式，所以我使用了猴子补丁（monkey patch）的形式为它默认设置使用了xpath在monkey_patching.py文件中。最新的提交在touero分支中，如果你能够使用我将合并它，请给我反馈，虽然还不是很完善，但是目前已经能够顺利运行，如果你有兴趣可以尝试提交pr。这是去年的老代码了，抱歉。

**Comment by M1saka10010** [comment]
railway_robot
124行附近修改如下
```python
                try:
                    site = f'//*[@id="erdeng1"]/ul/li/a[@id="1{self.info["seat"]}"]'
                    self.wait_click_xpath(site)
                except:
                    log('选座失败')
```

**Comment by touero** [comment]
> railway_robot 124行附近修改如下
> 
> ```python
>                 try:
>                     site = f'//*[@id="erdeng1"]/ul/li/a[@id="1{self.info["seat"]}"]'
>                     self.wait_click_xpath(site)
>                 except:
>                     log('选座失败')
> ```
此处若要捕获应捕获具体的异常`wait_click_xpath`会引发timeout的异常, click()也会引发元素不可用的异常

**Comment by M1saka10010** [comment]
> > railway_robot 124行附近修改如下
> > ```python
> >                 try:
> >                     site = f'//*[@id="erdeng1"]/ul/li/a[@id="1{self.info["seat"]}"]'
> >                     self.wait_click_xpath(site)
> >                 except:
> >                     log('选座失败')
> > ```
> 
> 此处若要捕获应捕获具体的异常`wait_click_xpath`会引发timeout的异常, click()也会引发元素不可用的异常

还有一些别的改动，等我成功抢票再一并pr吧TAT
